server:
  port: 2500
  token: "secret-token"
executor:
  job_queue: 500
  job_pool: 16
  run_queue: 500
  run_pool: 16
  extra_cpu_time: 1
  compile_timeout: 10
  compile_memory: 262144
  cpu_time_limit: 5
  memory_limit: 262144
